languageCode = "en-us"
title = "Sudeep LandingPage"
baseurl = "http://sudeep87.github.io/landinsite"
theme = "aerial"

[params]
  name = "Start Your Journey"
  about = "Travel &nbsp;&bull;&nbsp; Camping &nbsp;&bull;&nbsp; Trekking"
  copyright = "CopyRigth Under CCl license"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Home"
  icon = "home"
  link = "http://sudeep87.github.io/landinsite"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "http://sudeep87.github.io/landinsite"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "#"
